#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  May 27, 2021 05:55:06 PM -03  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 659x545+790+255
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Download Manager"
    vTcl:DefineAlias "$top" "topLevel" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu46 \
        -command cmdAddUrl -takefocus {} -text Download -state disabled 
    vTcl:DefineAlias "$top.tBu46" "btnDownload" vTcl:WidgetProc "topLevel" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Downloads 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "topLevel" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr49 \
        -background $vTcl(actual_gui_bg) -height 15 -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr49" "treeDownloadList" vTcl:WidgetProc "topLevel" 1

    .top44.scr49.01 configure -columns "Col1 Col2 Col3 Col4" \
        -height 4
        .top44.scr49.01 configure -columns {Col1 Col2 Col3 Col4}
        .top44.scr49.01 heading #0 -text {tree}
        .top44.scr49.01 heading #0 -anchor center
        .top44.scr49.01 column #0 -width 0
        .top44.scr49.01 column #0 -minwidth 0
        .top44.scr49.01 column #0 -stretch 0
        .top44.scr49.01 column #0 -anchor w
        .top44.scr49.01 heading Col1 -text {File}
        .top44.scr49.01 heading Col1 -anchor center
        .top44.scr49.01 column Col1 -width 290
        .top44.scr49.01 column Col1 -minwidth 120
        .top44.scr49.01 column Col1 -stretch 1
        .top44.scr49.01 column Col1 -anchor w
        .top44.scr49.01 heading Col2 -text {Time}
        .top44.scr49.01 heading Col2 -anchor center
        .top44.scr49.01 column Col2 -width 127
        .top44.scr49.01 column Col2 -minwidth 80
        .top44.scr49.01 column Col2 -stretch 0
        .top44.scr49.01 column Col2 -anchor w
        .top44.scr49.01 heading Col3 -text {Size}
        .top44.scr49.01 heading Col3 -anchor center
        .top44.scr49.01 column Col3 -width 132
        .top44.scr49.01 column Col3 -minwidth 20
        .top44.scr49.01 column Col3 -stretch 0
        .top44.scr49.01 column Col3 -anchor w
        .top44.scr49.01 heading Col4 -text {%}
        .top44.scr49.01 heading Col4 -anchor center
        .top44.scr49.01 column Col4 -width 60
        .top44.scr49.01 column Col4 -minwidth 20
        .top44.scr49.01 column Col4 -stretch 0
        .top44.scr49.01 column Col4 -anchor w
    ttk::progressbar $top.tPr50 \
        -length 210 
    vTcl:DefineAlias "$top.tPr50" "TProgressbar1" vTcl:WidgetProc "topLevel" 1
    labelframe $top.lab51 \
        -font TkDefaultFont -foreground black -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 100 -highlightcolor black \
        -width 623 
    vTcl:DefineAlias "$top.lab51" "frmProgress" vTcl:WidgetProc "topLevel" 1
    checkbutton $top.che52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Enter add url} -variable chkEnterVar 
    vTcl:DefineAlias "$top.che52" "chkUrlEnter" vTcl:WidgetProc "topLevel" 1
    text $top.tex45 \
        -background white -font TkTextFont -foreground black -height 114 \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 516 -wrap word 
    $top.tex45 configure -font "TkTextFont"
    $top.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "txtUrlText" vTcl:WidgetProc "topLevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu46 \
        -in $top -x 0 -relx 0.838 -y 0 -rely 0.044 -width 83 -relwidth 0 \
        -height 98 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.289 -width 0 -relwidth 0.119 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.scr49 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.333 -width 0 -relwidth 0.945 \
        -height 0 -relheight 0.247 -anchor nw -bordermode ignore 
    place $top.tPr50 \
        -in $top -x 0 -relx 0.655 -y 0 -rely 0.289 -width 0 -relwidth 0.32 \
        -height 19 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.6 -width 0 -relwidth 0.945 \
        -height 0 -relheight 0.183 -anchor nw -bordermode ignore 
    place $top.che52 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.222 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.051 -anchor nw -bordermode ignore 
    place $top.tex45 \
        -in $top -x 0 -relx 0.03 -y 0 -rely 0.018 -width 0 -relwidth 0.783 \
        -height 0 -relheight 0.209 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

