#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    May 27, 2021 05:55:06 PM -03  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from . import dw_gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    dw_gui_support.set_Tk_var()
    top = topLevel (root)
    dw_gui_support.init(root, top)
    root.mainloop()

w = None
def create_topLevel(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_topLevel(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    dw_gui_support.set_Tk_var()
    top = topLevel (w)
    dw_gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_topLevel():
    global w
    w.destroy()
    w = None

class topLevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("659x545+790+255")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(1,  1)
        top.title("Download Manager")
        top.configure(highlightcolor="black")

        self.btnDownload = ttk.Button(top)
        self.btnDownload.place(relx=0.838, rely=0.044, height=98, width=83)
        self.btnDownload.configure(command=dw_gui_support.cmdAddUrl)
        self.btnDownload.configure(takefocus="")
        self.btnDownload.configure(text='''Download''')
        self.btnDownload.configure(state='disabled')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.03, rely=0.29, height=25, width=78)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Downloads''')

        self.style.configure('Treeview',  font="TkDefaultFont")
        self.treeDownloadList = ScrolledTreeView(top)
        self.treeDownloadList.place(relx=0.027, rely=0.332, relheight=0.248
                , relwidth=0.945)
        self.treeDownloadList.configure(columns="Col1 Col2 Col3 Col4")
        # build_treeview_support starting.
        self.treeDownloadList.heading("#0",text="tree")
        self.treeDownloadList.heading("#0",anchor="center")
        self.treeDownloadList.column("#0",width="0")
        self.treeDownloadList.column("#0",minwidth="0")
        self.treeDownloadList.column("#0",stretch="0")
        self.treeDownloadList.column("#0",anchor="w")
        self.treeDownloadList.heading("Col1",text="File")
        self.treeDownloadList.heading("Col1",anchor="center")
        self.treeDownloadList.column("Col1",width="290")
        self.treeDownloadList.column("Col1",minwidth="120")
        self.treeDownloadList.column("Col1",stretch="1")
        self.treeDownloadList.column("Col1",anchor="w")
        self.treeDownloadList.heading("Col2",text="Time")
        self.treeDownloadList.heading("Col2",anchor="center")
        self.treeDownloadList.column("Col2",width="127")
        self.treeDownloadList.column("Col2",minwidth="80")
        self.treeDownloadList.column("Col2",stretch="0")
        self.treeDownloadList.column("Col2",anchor="w")
        self.treeDownloadList.heading("Col3",text="Size")
        self.treeDownloadList.heading("Col3",anchor="center")
        self.treeDownloadList.column("Col3",width="132")
        self.treeDownloadList.column("Col3",minwidth="20")
        self.treeDownloadList.column("Col3",stretch="0")
        self.treeDownloadList.column("Col3",anchor="w")
        self.treeDownloadList.heading("Col4",text="%")
        self.treeDownloadList.heading("Col4",anchor="center")
        self.treeDownloadList.column("Col4",width="60")
        self.treeDownloadList.column("Col4",minwidth="20")
        self.treeDownloadList.column("Col4",stretch="0")
        self.treeDownloadList.column("Col4",anchor="w")

        self.TProgressbar1 = ttk.Progressbar(top)
        self.TProgressbar1.place(relx=0.656, rely=0.29, relwidth=0.32
                , relheight=0.0, height=19)
        self.TProgressbar1.configure(length="210")

        self.frmProgress = tk.LabelFrame(top)
        self.frmProgress.place(relx=0.03, rely=0.6, relheight=0.183
                , relwidth=0.945)
        self.frmProgress.configure(relief='groove')
        self.frmProgress.configure(text='''Labelframe''')

        self.chkUrlEnter = tk.Checkbutton(top)
        self.chkUrlEnter.place(relx=0.03, rely=0.222, relheight=0.051
                , relwidth=0.162)
        self.chkUrlEnter.configure(activebackground="#f9f9f9")
        self.chkUrlEnter.configure(justify='left')
        self.chkUrlEnter.configure(text='''Enter add url''')
        self.chkUrlEnter.configure(variable=dw_gui_support.chkEnterVar)

        self.txtUrlText = tk.Text(top)
        self.txtUrlText.place(relx=0.03, rely=0.018, relheight=0.209
                , relwidth=0.783)
        self.txtUrlText.configure(background="white")
        self.txtUrlText.configure(font="TkTextFont")
        self.txtUrlText.configure(selectbackground="blue")
        self.txtUrlText.configure(selectforeground="white")
        self.txtUrlText.configure(wrap="word")

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





